#!/usr/bin/env bash
# Install and configure HAproxy load palancer
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo "\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 436228-web-01 18.234.253.190:80
    server 436228-web-02 107.21.181.103:80
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null 2>&1
sudo service haproxy restart
